name: Release

concurrency: release

# TODO - only on push to main
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest

    permissions:
      # To allow ciReleaseTagNextVersion to push a tag to the repo
      contents: write
      # required by configure-aws-credentials step
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          # We need the full set of tags to be able to calculate the next version.
          # Currently, that only seems to be possible by fetching the entire history of the repo.
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto
          cache: sbt

      - name: Install GPG
        run: sudo apt update && sudo apt install -y gnupg

      - name: Import PGP key
        run: echo $PGP_SECRET | gpg --batch --import --passphrase $PGP_PASSPHRASE
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}

      # See https://index.scala-lang.org/shiftleftsecurity/sbt-ci-release-early
      - name: SBT release
        run: sbt +clean +compile +test ciReleaseTagNextVersion ciReleaseSonatype
        env:
          # name part of user token
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          # password part of user token
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
